[package]
name = "rust-cli-app-template"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["cargo"] }
serde = { version = "1.0", features = ["serde_derive"] }
tmux_interface = "0.3"
toml = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
